resources:
  - ../base/application-controller
  - ../base/dex
  - ../base/repo-server
  - ../base/server
  - ../base/config
  - ../base/redis
  - ../crds
  - ../base/notification
  - ../base/applicationset-controller

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: argocd
      - op: remove
        path: /spec/template/spec/containers/0/securityContext

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: argocd
      - op: remove
        path: /spec/template/spec/containers/0/securityContext

  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: argocd
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/image
        value: argocd-job
      - op: remove
        path: /spec/template/spec/initContainers/0/securityContext
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-notifications-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: argocd
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
      - op: remove
        path: /spec/template/spec/securityContext
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-applicationset-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: argocd
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
